# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy dependencies definitions
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install and build
RUN npm install --ignore-scripts && npm run build

# Default command to start the MCP server over stdio
CMD ["node", "build/index.js"]
